### ISSUE TITLE
Bound method does not seem correct?

### ISSUE THREAD

**Issue by Xotic750** [es-shims/Array.prototype.findIndex#17]
https://github.com/paulmillr/Array.prototype.findIndex/blob/master/index.js#L14

Shouldn't this be?

`return getPolyfill.call(array, predicate);`

**Comment by ljharb** [comment]
whoops, yes. This is the same as https://github.com/paulmillr/Array.prototype.find/issues/20 with the same fix. I'll take care of this asap.

**Comment by ljharb** [comment]
Released as v2.0.1.

**Comment by Xotic750** [comment]
Ah yes, slicing the args makes much more sense. But I'm still a little confused by the method used in the bound function. Some of your polyfills are using `getPolyfill`, which use the native prototype method if available or the implementation if not. But then you have some that use `implementation`, like here, which never use the native if it is available. Is there some kind of logic with respect to this?

**Comment by ljharb** [comment]
Good point - I've made that optimization in other modules, but not yet in these. Incoming.

(not "ponyfills", that's a stupid word - shims self-install, polyfills don't)

**Comment by ljharb** [comment]
Released in v2.0.2
